# Generated by Django 5.1.4 on 2025-07-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useful_Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='meterials_video')),
                ('image', models.FileField(blank=True, null=True, upload_to='materials_photo')),
                ('app_link_name', models.CharField(blank=True, max_length=100, null=True)),
                ('app_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
