# Generated by Django 5.1.4 on 2025-07-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_useful_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='exercise_videos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='video_file',
        ),
    ]
