# Generated by Django 5.1.4 on 2025-07-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_exercisevideo_remove_exercise_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseVideo',
        ),
    ]
