# Generated by Django 5.1.4 on 2025-07-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_foodselection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugar',
            field=models.FloatField(default=0),
        ),
    ]
